FROM alpine:latest

RUN apk add --no-cache mariadb mariadb-client

RUN	mkdir /var/run/mysqld && \
	chown mysql:mysql /var/run/mysqld && \
	chmod 755 /var/run/mysqld

RUN	mysql_install_db --user=mysql --ldata=/var/lib/mysql/

COPY my.cnf /etc/mysql/my.cnf

EXPOSE 3306

# CMD ["/bin/sh"]
CMD ["mysqld"]