version: "3.9"

networks:
  net:

volumes:
  sql_vol:
    name: sql_vol
    driver: local
    driver_opts:
      device: ~/inception/srcs/requirements/mariadb2/db
      o: bind
      type: none

  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: ~/TEST
      o: bind
      type: none
  
services:
  nginx:
    depends_on:
      # - wordpress
      - wp_php-fpm
    container_name: nginx
    restart: unless-stopped
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx 
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx/conf/conf.d/nginx.conf:/etc/nginx/nginx.conf
      # - ~/inception/srcs/requirements/nginx/public:/var/www/public
      # - ~/inception/srcs/.www:/var/www/html
      - wordpress_vol:/var/www/html
      - ./fastcgi_params:/etc/nginx/conf.d/fastcgi_params
    networks:
      - net
    ports:
      - "443:443"

  wp_php-fpm:
    # image: php:7.4-fpm-alpine
    depends_on:
      - mysql
    container_name: wp_php-fpm
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile.wordpress 
    volumes:
      # - ~/inception/srcs/requirements/nginx/public:/var/www/public
      - ~/inception/srcs/requirements/wordpress/php-fpm.d/:/etc/php7/php-fpm.d/
      # - ./database:/var/lib/mysql
      - ~/inception/srcs/requirements/wordpress/wordpress/wp-config.php:/var/www/html/wp-config.php
      - wordpress_vol:/var/www/html
    networks:
      - net
    environment:
    #   WORDPRESS_DB_HOST: wp
    #   WORDPRESS_DB_NAME: db_name
    #   WORDPRESS_DB_USER: user_name
    #   WORDPRESS_DB_PASSWORD: user_pass
    #   WORDPRESS_TABLE_PREFIX: wp_
      MYSQL_ROOT_PASSWORD: my-secret-password

  # mysql:
  #   build: 
  #     context: ./requirements/mariadb2
  #     dockerfile: Dockerfile.mariadb 
  #   environment:
  #     # WORDPRESS_DB_HOST: mysql
  #     # WORDPRESS_DB_NAME: db_name
  #     # WORDPRESS_DB_USER: user_name
  #     # WORDPRESS_DB_PASSWORD: user_pass
  #     # WORDPRESS_TABLE_PREFIX: wp_
  #     MYSQL_ROOT_PASSWORD: my-secret-password
  #   volumes:
  #     - sql_vol:/var/lib/mysql
  #   networks:
  #     - net

  mysql:
    image: alpine:latest
    command: sh -c "apk add --no-cache mariadb mariadb-client && mkdir /var/run/mysqld && chown mysql:mysql /var/run/mysqld && chmod 755 /var/run/mysqld && \
             mysql_install_db --user=mysql && \
             chown -R mysql:mysql /var/lib/mysql && \
             /usr/bin/mysqld --user=mysql --skip-networking=0 --bind-address=0.0.0.0"
    ports:
      - "3306:3306"
    volumes:
      - sql_vol:/var/lib/mysql
      - ~/inception/srcs/requirements/mariadb2/config/mysqld.cnf:/etc/mysql/mariadb.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    networks:
      - net

    
  # mariadb:
  #   image: mariadb:10.6.4-focal
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=somewordpress
  #     - MYSQL_DATABASE=wordpress
  #     - MYSQL_USER=wordpress
  #     - MYSQL_PASSWORD=wordpress
  #   expose:
  #     - 3306
  #     - 33060
  #   networks:
  #     - net

  # mariadb:
  #   image: mariadb:10.6.4-focal
  #   command: '--default-authentication-plugin=mysql_native_password'
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=sqlroot
  #     - MYSQL_DATABASE=db_name
  #     - MYSQL_USER=user_name
  #     - MYSQL_PASSWORD=user_pass
  #   expose:
  #     - 3306
  #     - 33060

  # mysql:
  #   image: mariadb
  #   volumes:
  #     - /data/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mysql_root_pass
  #     MYSQL_DATABASE: db_name
  #     MYSQL_USER: user_name
  #     MYSQL_PASSWORD: user_pass
  #   restart: unless-stopped
  #   networks:
  #     - net
  
  # mariadb:
  #   container_name: mariadb
  #   restart: unless-stopped
  #   build: 
  #     context: ./requirements/mariadb
  #     dockerfile: Dockerfile.mariadb 
  #   volumes:
  #     - ~/inception/srcs/requirements/mariadb/conf:/etc/mysql
  #   ports:
  #     - "3306:3306"

  # wordpress:
  #     image: wordpress
  #     links:
  #     - mariadb:mysql
  #     environment:
  #     - WORDPRESS_DB_PASSWORD=password
  #     - WORDPRESS_DB_USER=root
  #     ports:
  #     - "80:80"
  #     volumes:
  #     - ./html:/var/www/html
  # mariadb:
  #     image: mariadb
  #     environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=wordpress
  #     volumes:
  #     - ./database:/var/lib/mysql

  # mysql:
  #   image: mysql:latest
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: somewordpress
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress

  # wordpress:
  #   depends_on:
  #     - mysql
  #   container_name: wordpress
  #   restart: unless-stopped
  #   image: wordpress:latest
  #   # build:
  #   #   context: ./requirements/wordpress
  #   #   dockerfile: Dockerfile.wordpress
  #   ports:
  #     - "8000:80"
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress
