version: "3.9"

services:
  nginx:
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/simple_docker_nginx_html/public:/var/www/public
      - ~/inception/srcs/requirements/nginx/conf/conf.d:/etc/nginx
      - ~/inception/srcs/requirements/tools:/etc/nginx/ssl
    container_name: my_nginx

