version: "3.9"

networks:
  net:

# volumes:
#   wordpess:
#     name: wordpress
#     driver_opts:
#         device: ~/wp

services:
  nginx:
    depends_on:
      - php-fpm
    container_name: nginx
    restart: unless-stopped
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx 
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx/conf/conf.d:/etc/nginx/conf.d
      - ~/inception/srcs/requirements/nginx/public:/var/www/public
      # - ~/inception/srcs/.www:/var/www/html
      - ./fastcgi_params:/etc/nginx/conf.d/fastcgi_params
    ports:
      - "443:443"

  php-fpm:
    image: php:7.4-fpm-alpine
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
  # mariadb:
  #   container_name: mariadb
  #   restart: unless-stopped
  #   build: 
  #     context: ./requirements/mariadb
  #     dockerfile: Dockerfile.mariadb 
  #   volumes:
  #     - ~/inception/srcs/requirements/mariadb/conf:/etc/mysql
  #   ports:
  #     - "3306:3306"

  # wordpress:
  #     image: wordpress
  #     links:
  #     - mariadb:mysql
  #     environment:
  #     - WORDPRESS_DB_PASSWORD=password
  #     - WORDPRESS_DB_USER=root
  #     ports:
  #     - "80:80"
  #     volumes:
  #     - ./html:/var/www/html
  # mariadb:
  #     image: mariadb
  #     environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_DATABASE=wordpress
  #     volumes:
  #     - ./database:/var/lib/mysql

  # mysql:
  #   image: mysql:latest
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: somewordpress
  #     MYSQL_DATABASE: wordpress
  #     MYSQL_USER: wordpress
  #     MYSQL_PASSWORD: wordpress

  # wordpress:
  #   depends_on:
  #     - mysql
  #   container_name: wordpress
  #   restart: unless-stopped
  #   image: wordpress:latest
  #   # build:
  #   #   context: ./requirements/wordpress
  #   #   dockerfile: Dockerfile.wordpress
  #   ports:
  #     - "8000:80"
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wordpress
  #     WORDPRESS_DB_PASSWORD: wordpress
  #     WORDPRESS_DB_NAME: wordpress
