version: "3.9"

networks:
  net:

volumes:
  sql_vol:
    name: sql_vol
    driver: local
    driver_opts:
      device: ~/inception/srcs/volumes/mysql
      o: bind
      type: none

  wordpress_vol:
    name: wordpress_vol
    driver: local
    driver_opts:
      device: ~/inception/srcs/volumes/wordpress
      o: bind
      type: none
  
services:
  nginx:
    depends_on:
      - wp_php-fpm
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx 
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx/conf/conf.d/nginx.conf:/etc/nginx/http.d/my.conf
      - wordpress_vol:/var/www/html
    networks:
      - net
    ports:
      - "443:443"
    restart: unless-stopped

  wp_php-fpm:
    depends_on:
      - mysql
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile.wordpress 
    volumes:
      - ~/inception/srcs/requirements/wordpress/php-fpm.d/:/etc/php7/php-fpm.d/
      - ~/inception/srcs/requirements/wordpress/wordpress/wp-config.php:/var/www/html/wp-config.php
      - wordpress_vol:/var/www/html
    env_file: .env
    networks:
      - net
    restart: unless-stopped

  mysql:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile.mariadb 
    container_name: mysql
    volumes:
      - sql_vol:/var/lib/mysql
      - ~/inception/srcs/requirements/mariadb/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ~/inception/srcs/requirements/mariadb/config/mysqld.cnf:/etc/mysql/mariadb.conf.d/mysqld.cnf
    env_file: .env
    networks:
      - net
    ports:
      - "3306:3306"
    restart: unless-stopped
