version: "3.9"

services:
  nginx:
    build: requirements/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ~/inception/srcs/requirements/tools:/etc/nginx/ssl/
    environment:
      FLASK_DEBUG: "true"

