version: "3.9"

networks:
  net:
    driver: bridge

volumes:
  sql_vol:
    driver_opts:
      device: /home/max/inception/srcs/volumes/mysql
      o: bind
      type: none

  wordpress_vol:
    driver_opts:
      device: /home/max/inception/srcs/volumes/wordpress
      o: bind
      type: none
  
services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress_php
      - adminer
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx 
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx/conf/conf.d/nginx.conf:/etc/nginx/http.d/my.conf
      - wordpress_vol:/var/www/html
    networks:
      - net
    ports:
      - "443:443"
    restart: unless-stopped

  wordpress_php:
    container_name: wordpress_php
    depends_on:
      - mysql
      # - gitea
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile.wordpress 
    volumes:
      - ~/inception/srcs/requirements/wordpress/php-fpm/php-fpm.d/:/etc/php7/php-fpm.d/
      - ~/inception/srcs/requirements/wordpress/php-fpm/php-fpm.conf:/etc/php7/php-fpm.conf
      - ~/inception/srcs/requirements/wordpress/wordpress/wp-config.php:/var/www/html/wp-config.php
      # - ~/inception/srcs/requirements/wordpress/redis/redis.conf:/etc/redis.conf
      - wordpress_vol:/var/www/html
    env_file: .env
    networks:
      - net
    ports:
      - 9000:9000
    restart: unless-stopped

  mysql:
    container_name: mysql
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile.mariadb 
    volumes:
      - sql_vol:/var/lib/mysql
    env_file: .env
    networks:
      - net
    ports:
      - 3306:3306
    restart: unless-stopped

  ftp:
    container_name: ftp
    depends_on: 
      - wordpress_php
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile.ftp
    volumes:
      - wordpress_vol:/var/ftp:ro
      - ~/inception/srcs/requirements/ftp/config/vsftpd.conf:/etc/vsftpd.conf
    env_file: .env
    networks:
      - net
    ports:
      - 20:20
      - 21:21
    restart: unless-stopped

  gitea:
    container_name: gitea
    depends_on: 
      - mysql
    build:
      context: ./requirements/gitea
      dockerfile: Dockerfile.gitea
    volumes:
      - ~/inception/srcs/requirements/gitea/config/app.ini:/usr/local/bin/custom/conf/app.ini
      # - wordpress_vol:/var/ftp:ro
      # - ~/inception/srcs/requirements/certs:/etc/ssl/private/
      # - ~/inception/srcs/requirements/ftp/config/vsftpd.conf:/etc/vsftpd.conf
    env_file: .env
    networks:
      - net
    ports:
      - 3000:3000
    restart: unless-stopped

  redis:
    container_name: redis
    depends_on: 
      - wordpress_php
    build:
      context: ./requirements/redis
      dockerfile: Dockerfile.redis
    volumes:
      - wordpress_vol:/var/www/html
      - ~/inception/srcs/requirements/redis/config/redis.conf:/etc/redis.conf
    env_file: .env
    networks:
      - net
    ports:
      - 6379:6379
    restart: unless-stopped

  adminer:
    container_name: adminer
    depends_on: 
      - wordpress_php
      - mysql
      - gitea
    build:
      context: ./requirements/adminer
      dockerfile: Dockerfile.adminer
    volumes:
      - ~/inception/srcs/requirements/adminer/php-fpm/php-fpm.d/:/etc/php7/php-fpm.d/
      - ~/inception/srcs/requirements/adminer/php-fpm/php-fpm.conf:/etc/php7/php-fpm.conf
    env_file: .env
    networks:
      - net
    ports:
      - 9001:9001
    restart: unless-stopped

  nginx_portfolio:
    container_name: nginx_portfolio
    build: 
      context: ./requirements/nginx_portfolio
      dockerfile: Dockerfile.nginx_portfolio
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx_portfolio/conf/conf.d/nginx.conf:/etc/nginx/http.d/my.conf
      - ~/inception/srcs/requirements/nginx_portfolio/portfolio.html:/var/www/html/index.html
    networks:
      - net
    ports:
      - "801:801"
    restart: unless-stopped