version: "3.9"

networks:
  net:
    driver: bridge

volumes:
  sql_vol:
    driver_opts:
      device: /home/max/inception/srcs/volumes/mysql
      o: bind
      type: none

  wordpress_vol:
    driver_opts:
      device: /home/max/inception/srcs/volumes/wordpress
      o: bind
      type: none
  
services:
  nginx:
    container_name: nginx
    depends_on:
      - wp_php-fpm
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile.nginx 
    volumes:
      - ~/inception/srcs/requirements/certs:/etc/nginx/ssl
      - ~/inception/srcs/requirements/nginx/conf/conf.d/nginx.conf:/etc/nginx/http.d/my.conf
      - wordpress_vol:/var/www/html
    networks:
      - net
    ports:
      - "443:443"
    restart: unless-stopped

  wp_php-fpm:
    container_name: wp_php
    depends_on:
      - mysql
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile.wordpress 
    volumes:
      - ~/inception/srcs/requirements/wordpress/php-fpm.d/:/etc/php7/php-fpm.d/
      - ~/inception/srcs/requirements/wordpress/wordpress/wp-config.php:/var/www/html/wp-config.php
      - ~/inception/srcs/requirements/wordpress/redis/redis.conf:/etc/redis.conf
      - wordpress_vol:/var/www/html
    env_file: .env
    networks:
      - net
    restart: unless-stopped

  mysql:
    container_name: mysql
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile.mariadb 
    volumes:
      - sql_vol:/var/lib/mysql
      - ~/inception/srcs/requirements/mariadb/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ~/inception/srcs/requirements/mariadb/config/mysqld.cnf:/etc/mysql/mariadb.conf.d/mysqld.cnf
    env_file: .env
    networks:
      - net
    ports:
      - "3306:3306"
    restart: unless-stopped

  ftp:
    container_name: ftp
    depends_on: 
      - wp_php-fpm
    build:
      context: ./requirements/ftp
      dockerfile: Dockerfile.ftp
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    volumes:
      - wordpress_vol:/var/ftp:ro
      # - ~/inception/srcs/requirements/certs:/etc/ssl/private/
      - ~/inception/srcs/requirements/ftp/config/vsftpd.conf:/etc/vsftpd.conf
    env_file: .env
    networks:
      - net
    restart: unless-stopped