FROM		alpine:3.16

RUN			apk add git sqlite openssh-client ca-certificates

RUN			wget https://dl.gitea.io/gitea/1.14.5/gitea-1.14.5-linux-amd64 -O /usr/local/bin/gitea \
			&& chmod +x /usr/local/bin/gitea

ENTRYPOINT ["/usr/local/bin/gitea"]