FROM		alpine:3.16

RUN			apk add openrc mariadb mariadb-client

RUN			mysql_install_db --user=mysql --ldata=/var/lib/mysql/ \
			&& mkdir /var/run/mysqld \
			&& chown mysql:mysql /var/run/mysqld \
			&& chmod 755 /var/run/mysqld \
			&& mysql_install_db --user=mysql \
			&& chown -R mysql:mysql /var/lib/mysql

COPY		entrypoint.sh /entrypoint.sh

ENTRYPOINT	["/entrypoint.sh"]