FROM alpine:latest

RUN apk add --no-cache zsh openrc mariadb mariadb-client

RUN	mysql_install_db --user=mysql --ldata=/var/lib/mysql/

RUN	mkdir /var/run/mysqld && \
	chown mysql:mysql /var/run/mysqld && \
	chmod 755 /var/run/mysqld && \
	mysql_install_db --user=mysql && \
	chown -R mysql:mysql /var/lib/mysql

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]