CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER '$MYSQL_ROOT_USER'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON '$DB_NAME'.* TO '$MYSQL_ROOT_USER'@'%';
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON '$DB_NAME'.* TO '$DB_PASSWORD'@'%';
FLUSH PRIVILEGES;