FROM		alpine:3.16

RUN 		apk add vsftpd

RUN			mkdir -p /var/run/vsftpd/empty \
			&& mkdir -p /etc/vsftpd \
			&& mkdir -p /var/ftp \
			&& mv /etc/vsftpd.conf /etc/vsftpd.orig; true \
			&& adduser -D -g '' -G www-data www-data

COPY		config/vsftpd.conf /etc/vsftpd.conf
COPY		entrypoint.sh /entrypoint.sh

RUN			chmod +x /entrypoint.sh

ENTRYPOINT	["/entrypoint.sh"]
