FROM		alpine:3.15

RUN			apk add zsh nano curl wget php7 php7-fpm php7-mysqli php7-dom php7-xml php7-xmlwriter php7-curl php7-json php7-tokenizer php7-simplexml php7-redis redis mysql-client php7 php7-fpm php7-mysqli php7-session php7-json php7-mbstring php7-gd

RUN			mkdir -p /var/www/html

RUN			wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-en.php -O /var/www/html/adminer.php


CMD			["redis-server", "/etc/redis.conf"]